import { createClient, SupabaseClient } from '@supabase/supabase-js';

// Supabase configuration
const supabaseUrl = (import.meta as any).env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = (import.meta as any).env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('⚠️ Missing Supabase environment variables.');
  console.error('Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your .env.local file.');
  console.error('Current values:', { 
    url: supabaseUrl ? '✓ Set' : '✗ Missing', 
    key: supabaseAnonKey ? '✓ Set' : '✗ Missing' 
  });
} else {
  console.log('✓ Supabase configuration loaded');
  console.log('URL:', supabaseUrl);
  console.log('Key format:', supabaseAnonKey.startsWith('sb_') ? 'New format (sb_publishable)' : 'Legacy JWT format');
}

// Create Supabase client
export const supabase: SupabaseClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true
    }
});

// Database types (will be auto-generated by Supabase CLI in production)
export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string;
                    username: string | null;
                    full_name: string | null;
                    avatar_url: string | null;
                    phone: string | null;
                    location: string | null;
                    bio: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
                Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
            };
            pets: {
                Row: {
                    id: string;
                    name: string;
                    breed: string;
                    age: string;
                    gender: 'male' | 'female';
                    type: 'dog' | 'cat' | 'rabbit' | 'bird' | 'turtle' | 'hamster';
                    weight: string | null;
                    description: string | null;
                    location: string | null;
                    latitude: number | null;
                    longitude: number | null;
                    distance: string | null;
                    shelter_name: string | null;
                    shelter_avatar: string | null;
                    posted_time: string;
                    tags: string[] | null;
                    status: 'available' | 'pending' | 'adopted';
                    owner_id: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['pets']['Row'], 'id' | 'created_at' | 'updated_at'>;
                Update: Partial<Database['public']['Tables']['pets']['Insert']>;
            };
            favorites: {
                Row: {
                    id: string;
                    user_id: string;
                    pet_id: string;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['favorites']['Row'], 'id' | 'created_at'>;
                Update: Partial<Database['public']['Tables']['favorites']['Insert']>;
            };
            applications: {
                Row: {
                    id: string;
                    user_id: string;
                    pet_id: string | null;
                    type: 'adoption' | 'hosting' | 'rehome';
                    status: 'pending' | 'approved' | 'rejected';
                    form_data: any;
                    submitted_at: string;
                    reviewed_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['applications']['Row'], 'id' | 'created_at' | 'updated_at'>;
                Update: Partial<Database['public']['Tables']['applications']['Insert']>;
            };
            conversations: {
                Row: {
                    id: string;
                    participant_1_id: string;
                    participant_2_id: string;
                    pet_id: string | null;
                    last_message_at: string;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['conversations']['Row'], 'id' | 'created_at'>;
                Update: Partial<Database['public']['Tables']['conversations']['Insert']>;
            };
            messages: {
                Row: {
                    id: string;
                    conversation_id: string;
                    sender_id: string;
                    content: string;
                    is_read: boolean;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'>;
                Update: Partial<Database['public']['Tables']['messages']['Insert']>;
            };
        };
    };
}
